name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: pm2 restart server.js
      - name: Print Success Response
        run: echo "Workflow ran successfully!"

  pull_request:
    branches: ["master"]
    jobs:
      - name: Pull Request Check
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Print Success Response
            run: echo "Pull request check ran successfully!"
